AUGMENTATION: True
BATCH_SIZE: 32
IMAGE_SIZE: [224, 224, 3]
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 15
WEIGHTS: imagenet
LEARNING_RATE: 0.00001

torch:
  AUGMENTATION: True
  BATCH_SIZE: 32
  IMAGE_SIZE: [3, 224, 224]
  EPOCHS: 10
  CLASSES: 15
  WEIGHTS: IMAGENET1K_V1
  LEARNING_RATE: 0.00001