artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion/data
  

base_model_config:
  root_dir: artifacts/models
  base_model_path: artifacts/models/base_model.h5
  updated_base_model_path: artifacts/models/updated_base_model.h5

callback_config:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log
  checkpoint_model_path: artifacts/callbacks/checkpoint/model.h5

model_trainer_config:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.h5