artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion/data
  

base_model_config:
  root_dir: artifacts/models
  base_model_path: artifacts/models/base_model.keras
  updated_base_model_path: artifacts/models/updated_base_model.keras

callback_config:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log
  checkpoint_model_path: artifacts/callbacks/checkpoint/model.keras